package ftd2xx;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : lib\ftd2xx\ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("ftd2xx") 
public class FT_DEVICE_LIST_INFO_NODE extends StructObject {
	static {
		BridJ.register();
	}
	@CLong 
	@Field(0) 
	public long Flags() {
		return this.io.getCLongField(this, 0);
	}
	@CLong 
	@Field(0) 
	public FT_DEVICE_LIST_INFO_NODE Flags(long Flags) {
		this.io.setCLongField(this, 0, Flags);
		return this;
	}
	@CLong 
	@Field(1) 
	public long Type() {
		return this.io.getCLongField(this, 1);
	}
	@CLong 
	@Field(1) 
	public FT_DEVICE_LIST_INFO_NODE Type(long Type) {
		this.io.setCLongField(this, 1, Type);
		return this;
	}
	@CLong 
	@Field(2) 
	public long ID() {
		return this.io.getCLongField(this, 2);
	}
	@CLong 
	@Field(2) 
	public FT_DEVICE_LIST_INFO_NODE ID(long ID) {
		this.io.setCLongField(this, 2, ID);
		return this;
	}
	@Field(3) 
	public int LocId() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public FT_DEVICE_LIST_INFO_NODE LocId(int LocId) {
		this.io.setIntField(this, 3, LocId);
		return this;
	}
	/** C type : char[16] */
	@Array({16}) 
	@Field(4) 
	public Pointer<Byte > SerialNumber() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : char[64] */
	@Array({64}) 
	@Field(5) 
	public Pointer<Byte > Description() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : FT_HANDLE */
	@Field(6) 
	public Pointer<? > ftHandle() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : FT_HANDLE */
	@Field(6) 
	public FT_DEVICE_LIST_INFO_NODE ftHandle(Pointer<? > ftHandle) {
		this.io.setPointerField(this, 6, ftHandle);
		return this;
	}
	public FT_DEVICE_LIST_INFO_NODE() {
		super();
	}
	public FT_DEVICE_LIST_INFO_NODE(Pointer pointer) {
		super(pointer);
	}
}
