package ftd2xx;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Bits;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : lib\ftd2xx\ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("ftd2xx") 
public class FTCOMSTAT extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	@Bits(1) 
	public int fCtsHold() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	@Bits(1) 
	public FTCOMSTAT fCtsHold(int fCtsHold) {
		this.io.setIntField(this, 0, fCtsHold);
		return this;
	}
	@Field(1) 
	@Bits(1) 
	public int fDsrHold() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	@Bits(1) 
	public FTCOMSTAT fDsrHold(int fDsrHold) {
		this.io.setIntField(this, 1, fDsrHold);
		return this;
	}
	@Field(2) 
	@Bits(1) 
	public int fRlsdHold() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	@Bits(1) 
	public FTCOMSTAT fRlsdHold(int fRlsdHold) {
		this.io.setIntField(this, 2, fRlsdHold);
		return this;
	}
	@Field(3) 
	@Bits(1) 
	public int fXoffHold() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	@Bits(1) 
	public FTCOMSTAT fXoffHold(int fXoffHold) {
		this.io.setIntField(this, 3, fXoffHold);
		return this;
	}
	@Field(4) 
	@Bits(1) 
	public int fXoffSent() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	@Bits(1) 
	public FTCOMSTAT fXoffSent(int fXoffSent) {
		this.io.setIntField(this, 4, fXoffSent);
		return this;
	}
	@Field(5) 
	@Bits(1) 
	public int fEof() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	@Bits(1) 
	public FTCOMSTAT fEof(int fEof) {
		this.io.setIntField(this, 5, fEof);
		return this;
	}
	@Field(6) 
	@Bits(1) 
	public int fTxim() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	@Bits(1) 
	public FTCOMSTAT fTxim(int fTxim) {
		this.io.setIntField(this, 6, fTxim);
		return this;
	}
	@Field(7) 
	@Bits(25) 
	public int fReserved() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	@Bits(25) 
	public FTCOMSTAT fReserved(int fReserved) {
		this.io.setIntField(this, 7, fReserved);
		return this;
	}
	@Field(8) 
	public int cbInQue() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public FTCOMSTAT cbInQue(int cbInQue) {
		this.io.setIntField(this, 8, cbInQue);
		return this;
	}
	@Field(9) 
	public int cbOutQue() {
		return this.io.getIntField(this, 9);
	}
	@Field(9) 
	public FTCOMSTAT cbOutQue(int cbOutQue) {
		this.io.setIntField(this, 9, cbOutQue);
		return this;
	}
	public FTCOMSTAT() {
		super();
	}
	public FTCOMSTAT(Pointer pointer) {
		super(pointer);
	}
}
